### ISSUE TITLE
Nest Developer Page Change

### ISSUE THREAD

**Issue by DeaFroggatt** [zpeters/nerdnest#16] opened 2018-05-18 18:46 UTC
Followed procedures to create Nest Developers Account on the nerdnest wiki..  Although the Product Details and steps that now appear at https://developers.nest.com do not appear as indicated on the page created by Zach Peters, Feb 2, 2017.
Subsequently I had difficulty completing the step "Registering nerdnest with your account".  The Authorization URL took me to a page unrecognized page.
Is there a revised version to these instructions that match the current Nest Developer page??

**Comment by zpeters** [comment] 2018-05-19 01:50
Dupe of #15

**Closed as completed by zpeters** 2018-05-19 01:50 UTC
